---
name: Deploy to Github Pages

on:
  workflow_run:
    workflows:
      - Build Site
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Build Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: production-files
          repo: pio-mahusai/github-actions-exercise
          workflow: build.yaml
          path: ./dist
          search_artifacts: true
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
