---
name: Pull Request Format

on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Format files
        run: pnpm format
